### ISSUE TITLE
プロジェクト支援について 

### ISSUE THREAD

**Issue by fujiwaraizuho** [Syow3525/Server-#4]
## **プロジェクト支援について**
@Syow3525 
Lobiでの話し合いを拝見させていただきました藤原です。
Syow3525様の提案された中継サーバー、
今のPMMP界に新しい風を吹かせる素晴らしいサービスかもしれません。
そのプロジェクトに共感し、Syow3525様に了承をいただけるのであればこのプロジェクトに関する資金を提供させていただきたいと思っております。
ご検討ください

**Comment by Syow3525** [comment]
はい
是非ご協力ください！
資金提供とはどのようなものかわかりませんが
お願いいたします！

おねがいなのですが
中継サーバーで他のサーバーへ行くための鯖移動プラグイン
経済が共有されるプラグインがあればもっと中継サーバーや他のサーバーに運気をもたらすかもしれません
無理ならば良いですが作成をお願いしたいです

サーバー移動プラグインは他の方が来週作ると言ってらっしゃるので経済共有の方をお願い致します

**Comment by Syow3525** [comment]
偉そうに言ってしまいすみません

**Comment by fujiwaraizuho** [comment]
なんの要素を、サーバー間で共有すべきなのかを教えてくだされば、プロジェクトが進めやすいです。
また、共有するためにはネットワークに加盟するサーバーの数にもよりますが、おそらく大規模なDBサーバーが必要となります。
その点ご了承頂けますか？

**Comment by Syow3525** [comment]
某バン共有サイトみたいなのが必要ですよね...
共有されるのはお金だけでまずは大丈夫かと考えてます

**Comment by Syow3525** [comment]
お金関連が共有されたら他の鯖でもお金貯められるので
いいと思います

チャットも共有したらすごい面白そうなのですが共有なんてできますかね？
遅延があるのはほぼ確定ですよね

**Comment by Syow3525** [comment]
DBのけんについてですが
自分のPCで
持つならばいけると思います

**Comment by Syow3525** [comment]
容量はある方です(容量関係あるのかわかりませんが)
